// <auto-generated />
namespace BTL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_relationship_manufacturer_picture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_relationship_manufacturer_picture));
        
        string IMigrationMetadata.Id
        {
            get { return "202204061410039_add_relationship_manufacturer_picture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
