// <auto-generated />
namespace BTL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removefileNamecategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removefileNamecategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202204040358005_remove-fileName-category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
